accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"
urlpatterns = [
   # profile management urls
   path("user/profile/<int:pk>",views.UserProfile.as_view(),name="user-profile"),
   path("update/<int:pk>",views.Update.as_view(),name="update"),
   # authentication urls
   path("login/",views.Login.as_view(),name="login"),
   path("logout/",views.Logout.as_view(),name="logout"),
   path("register/",views.Register.as_view(),name="register"),
   # password management urls
   path("password/change/<int:pk>",views.PasswordChange.as_view(),name="password_change"),
   path("send/password/reset/mail/",views.SendPasswordResetMail.as_view(),name="send_password_reset_mail"),
   path("password/reset/<str:token>",views.PasswordReset.as_view(),name="password_reset/"),
]

mysite/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include,path
from django.conf import settings

urlpatterns = [
    path("accounts/",include('accounts.urls')),
    path("",include('newsapp.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsapp/urls.py
from django.urls import path
from . import views

app_name="newsapp"
urlpatterns=[
    # home page url
    path("",views.Index.as_view(),name="Index"),
    # articles urls
    path("article/<slug:slug>/",views.NewsDetail.as_view(),name="NewsDetail"),
    path("article/category/<slug:slug>/",views.NewsByCategory.as_view(),name="NewsByCategory"),
    path("search/",views.Search.as_view(),name="Search"),
    path("create/article",views.CreateArticle.as_view(),name="CreateArticle"),
    path("more/add/article/<slug:slug>",views.MoreContentAdd.as_view(),name="MoreContentAdd"),
    path("update/article/<slug:slug>",views.UpdateArticle.as_view(),name="UpdateArticle"),
    path("delete/article/<slug:slug>",views.DeleteArticle.as_view(),name="DeleteArticle"),
    # accounts urls
]       

newsapp/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

# article category model
class Category(models.Model):
        category=models.CharField(max_length=200)
        slug=models.SlugField(unique=True,max_length=400)
        class Meta:
            verbose_name = "category"
            verbose_name_plural = "categories"
        def __str__(self):
            return self.category 

# article model
class Article(models.Model):
    title=models.CharField(max_length=200)
    short_description=models.CharField(max_length=400)
    author=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    paragraph=models.TextField(max_length=2000)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to="article/images")
    slug=models.SlugField("Permalink",unique=True,max_length=400)
    last_updated=models.DateTimeField(auto_now=True)
    published=models.BooleanField(default=False)
    class Meta:
        verbose_name = "article"
        verbose_name_plural = "articles"
        ordering = ["-last_updated"]
    def __str__(self):
        return  self.title
    def get_absolute_url(self):
        return reverse('newsapp:NewsDetail', kwargs={'slug': self.slug})

# more content to the article
class MoreContent(models.Model):
    author=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    article=models.ForeignKey(Article,on_delete=models.CASCADE)
    image=models.ImageField(upload_to="article/images",null=True,blank=True)
    short_description=models.CharField(max_length=200)
    paragraph=models.TextField(max_length=2000)
    class Meta:
        verbose_name = "more cotent for articles"
        verbose_name_plural = "more cotent for articles"
    def __str__(self):
        return self.short_description

newsapp/forms.py
from django.forms import *
from .models import Article,MoreContent

class ArticleForm(ModelForm):
    class Meta:
        model=Article
        fields=['title','short_description','paragraph','category','image','slug']
        widgets={
            'title':TextInput(attrs={"placeholder":"Article Title","class":"form-input"}),
            'short_description':TextInput(attrs={"placeholder":"Article short_description","class":"form-input"}),
            'paragraph':Textarea(attrs={"placeholder":"Article Title","rows":5,"class":"form-input"}),
            'category':Select(attrs={"placeholder":"Article Category","class":"form-input"}),
            'slug':TextInput(attrs={"placeholder":"Article Slug","class":"form-input"})  
    }

class MoreContentForm(ModelForm):
    class Meta:
         model=MoreContent
         fields=['image','short_description','paragraph']
         widgets={
            'short_description':TextInput(attrs={"placeholder":"Short Description","class":"form-input"}),
            'paragraph':Textarea(attrs={"placeholder":" paragraph","rows":5,"class":"form-input"}),
    }

class ArticleUpdateForm(ModelForm):
    class Meta:
        model=Article
        fields=['title','short_description','paragraph','image','slug']
        widgets={
           'title':TextInput(attrs={"placeholder":"Article Title","class":"form-input"}),
            'short_description':TextInput(attrs={"placeholder":"Article short_description","class":"form-input"}),
            'paragraph':Textarea(attrs={"placeholder":"Article Title","rows":5,"class":"form-input"}),
            'category':Select(attrs={"placeholder":"Article Category","class":"form-input"}),
            'slug':TextInput(attrs={"placeholder":"Article Slug","class":"form-input"})  
    }

newsapp/views.py
from django.urls import reverse_lazy
from django.shortcuts import redirect,render
from django.views.generic import ListView,DetailView,TemplateView,CreateView,UpdateView,DeleteView,FormView
from .models import Article,Category,MoreContent
from django.db.models import Q 
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import ArticleForm,ArticleUpdateForm,MoreContentForm
from django.forms import modelformset_factory
from django.http import Http404,HttpResponse
from django.contrib import messages

# staff mixin
class CheckStaffMixin(LoginRequiredMixin):
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_superuser or request.user.is_staff :
            return super().dispatch(request, *args, **kwargs)
        messages.info(self.request,"Sorry ! must me a staff or admin")
        return redirect("newsapp:Index")

#home page view
class Index(ListView):
    model=Article
    context_object_name='articles'
    template_name="newsapp/index.html"
    paginate_by=10  
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories']=Category.objects.all()[:5]
        return context

#news detail view
class NewsDetail(DetailView):
    model=Article
    context_object_name="article"
    template_name="newsapp/article_detail.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['related_news'] = Article.objects.filter(category__category__contains=self.object.category).exclude(slug=self.object.slug)[:3]
        context['categories']=Category.objects.all()[:5]
        context['more_news']=Article.objects.all().exclude(category=self.object.category)[:8]
        context['more_detail']=MoreContent.objects.filter(article=self.object)
        return context
# news by category
class NewsByCategory(ListView):
    model=Category
    template_name="newsapp/index.html"
    paginate_by=10
    context_object_name="articles"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories']=Category.objects.all()[:5]
        return context
    def get_queryset(self, *args, **kwargs):
        category=Category.objects.get(slug=self.kwargs['slug'])
        return Article.objects.filter(category__category__contains=category.category)

#search view
class Search(ListView):
    model=Article
    template_name="newsapp/index.html"
    context_object_name="articles"
    paginate_by=10  
    def get_queryset(self):
        query = self.request.GET.get("search")
        return Article.objects.filter(Q(title__icontains=query)|Q(short_description__icontains=query) | Q(paragraph__icontains=query))
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories']=Category.objects.all()[:5]
        return context

#create news view
class CreateArticle(CheckStaffMixin,CreateView):
    model=Article
    form_class=ArticleForm
    template_name="newsapp/create_article.html"
    def form_valid(self, form):
       article=form.save(commit=False)
       article.author=self.request.user
       article.save()
       messages.info(self.request,"new article added")
       return redirect("newsapp:MoreContentAdd",article.slug)

class MoreContentAdd(CheckStaffMixin,FormView):
    form_class=MoreContentForm
    template_name="newsapp/morenewsform.html"
    def get(self, request, *args, **kwargs):
        try:
            Article.objects.get(slug=kwargs['slug'])
        except:
            messages.info(request,"article not found")
            return redirect("newsapp:Index")
        return super().get(request,*args,**kwargs)
    def form_valid(self, form):
       article=Article.objects.get(slug=self.kwargs['slug'])
       more_content=form.save(commit=False)
       more_content.article=article
       more_content.author=self.request.user
       more_content.save()
       messages.info(self.request,"more images and paragraphs added")
       return redirect("newsapp:MoreContentAdd",article.slug)

#edit news view
class UpdateArticle(CheckStaffMixin,UpdateView):
    model=Article
    form_class=ArticleUpdateForm
    template_name="newsapp/update_article.html"
    Factoryformmodel=modelformset_factory(MoreContent,form=MoreContentForm,extra=1)
    def get(self, request, *args, **kwargs):
        try:
            Article.objects.get(slug=kwargs['slug'])
        except:
            messages.info(request,"article not found")
            return redirect("newsapp:Index")
        return super().get(request,*args,**kwargs)

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        formset=self.Factoryformmodel(queryset=self.get_object().morecontent_set.all())
        context['formset']=formset
        return context

    def form_valid(self, form):
        formset=self.Factoryformmodel(self.request.POST,self.request.FILES ,queryset=self.get_object().morecontent_set.all())
        form.save()
        try:
            if formset.is_valid():
                for form in formset:
                    child=form.save(commit=False)
                    child.article=self.object
                    child.author=self.request.user
                    child.save()   
            messages.info(self.request,"article updated")
            return redirect("newsapp:UpdateArticle",self.object.slug)
        except Exception as err:
            messages.info(self.request,"article failed update")
            return redirect("newsapp:UpdateArticle",self.object.slug)

#delete news view
class DeleteArticle(CheckStaffMixin,DeleteView):
    model=Article
    template_name="newsapp/delete_article.html"
    success_url=reverse_lazy("newsapp:Index")
    def delete(self,request):
        messages.info(self.request,"article deleted")
        return super().delete(request)

newsapp/templates/newsapp/article_detail.html
{%extends 'newsapp/index.html' %} {%block body%}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8">
      <div class="news-detail">
        <div class="news-detail-container">
          <h1 class="big-title">{{article.title|truncatechars:60}}</h1>
          <div class="news-detail-imageWrapper">
            <img src="{{article.image.url}}" class="card-img-top" alt="..." />
            <p class="date text-secondary">
              Last Updated : {{article.last_updated|date:"M d, Y"}}
            </p>
            <p class="subtitle">
              {{article.short_description|truncatechars:100}}
            </p>
            <p class="content">{{article.paragraph}}</p>
          </div>
          {%for more in more_detail%}
          <p class="subtitle">{{more.short_description|truncatechars:100}}</p>
          <div class="news-detail-imageWrapper">
            {%if more.image%}
            <img src="{{more.image.url}}" class="card-img-top" alt="..." />
            {%endif%}
            <p class="content">{{more.paragraph}}</p>
          </div>
          {%endfor%}
        {%if user.is_staff%}
          <a
            class="update"
            href="{% url 'newsapp:UpdateArticle' article.slug %}"
            >Update</a
          >
          <a
            class="delete"
            href="{% url 'newsapp:DeleteArticle' article.slug %}"
            >Delete</a
          >
{%endif%}

        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="related_item">
        <h1 class="bg-light text-secondary section-heading">Related News</h1>
        {%for article in related_news%}
        <div>
          <a href="{% url 'newsapp:NewsDetail' article.slug  %}">
            <img src="{{article.image.url}}" class="card-img-top" alt="..." />
            <p class="date text-secondary">
              <i>Last Updated : {{article.last_updated|date:"M d, Y"}}</i>
            </p>
            <p class="subtitle">
              {{article.short_description|truncatechars:80}}
            </p>
          </a>
        </div>
        {%endfor%}
      </div>
    </div>
  </div>
</div>
<!-- more articles -->

<h1 class="bg-light text-secondary section-heading">Popular Articles</h1>
<div class="gallery-grid">
  {% for article in more_news %}
  <div class="cards">
    <a href="{% url 'newsapp:NewsDetail' article.slug  %}">
      <img src="{{article.image.url}}" class="card-img-top" alt="..." />
      <p class="date text-secondary">
        <i> Last Updated : {{article.last_updated|date:"M d, Y"}}</i>
      </p>
      <p class="title">{{article.title|truncatechars:50}}</p>
    </a>
  </div>
  {%endfor%}
</div>
{%endblock%}

newsapp/templates/newsapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- title -->
    {%block title%} {%endblock%}
    <!-- styles -->
    {%block styles%} {%endblock%}
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />
    <script src="https://unpkg.com/htmx.org@1.8.4"></script>
  </head>

  <body>
    <!-- navbar -->
    {%block navbar%} {%endblock%} {%include "newsapp/messages.html" %}
    <!-- body -->
    {%block body%}{%endblock%}
    <!-- footer -->
    {%block footer %} {%endblock%}
    <!-- script -->
    {%block script%}
    <script src="{%static 'js/bootstrap.bundle.min.js' %}"></script>
    {%endblock%}
  </body>
</html>

newsapp/templates/newsapp/base_form.html
{%extends 'newsapp/index.html' %} {%block body%}
<!--  -->
<div class="form-wrapper">
  <form class="crud-form" method="post" enctype="multipart/form-data">
    <h3 class="section-heading">{%block form-heading%}{%endblock%}</h3>
    {%csrf_token%}
    <!--  -->
    {{form.as_div}} {%block moreform%} {%endblock%}
    <button type="submit">Submit</button>
    <!--  -->
    {%block formfooter%}
    {%endblock%}
  </form>
</div>
{%endblock%}

newsapp/templates/newsapp/create_article.html
{%extends 'newsapp/base_form.html' %}
<!-- form-heading -->
{%block form-heading%} Create New Article {%endblock%} {%block buttons%}
<button type="submit">Submit</button>
{%endblock%}
<!-- form footer -->
{%block formfooter%}
<a class="delete" href="/">Cancel</a>
{%endblock%}

newsapp/templates/newsapp/delete_article.html
{%extends 'newsapp/base_form.html' %}
<!-- form-heading -->
<!-- form-heading -->
{%block form-heading%}
<span class="text-danger"">Are you Sure to Delete This Article ?</span>
{%endblock%}
<!-- form footer -->
{%block formfooter%}
<a href="/">Cancel</a>
{%endblock%}

newsapp/templates/newsapp/footer.html
<footer>
  <!-- Footer -->
  <footer class="text-center text-lg-start bg-light text-muted">
    <div>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-google"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-github"></i>
      </a>
    </div>
    <section class="">
      <div class="container text-center text-md-start mt-5">
        <!-- Grid row -->
        <div class="row mt-3">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <!-- Content -->
            <h6 class="text-uppercase fw-bold mb-4">
              <i class="fas fa-gem me-3"></i>Company name
            </h6>
            <p>
              agna aliqua. Risus in hendrerit gravida rutrum quisque non tellus.
              Semper quis lectus nulla at. Sagittis id consectetur purus ut
              faucibus pulvinar. Diam quis enim lobortis scelerisque fermentum
              dui.
            </p>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">Connect Us</h6>
            <p>
              <a href="#!" class="text-reset">Twitter</a>
            </p>
            <p>
              <a href="#!" class="text-reset">YouTube</a>
            </p>
            <p>
              <a href="#!" class="text-reset">LiveTV</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Others</a>
            </p>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">Useful links</h6>
            <p>
              <a href="/technology" class="text-reset">Technology</a>
            </p>
            <p>
              <a href="/business" class="text-reset">Business</a>
            </p>
            <p>
              <a href="/bollywood" class="text-reset">Bollywood</a>
            </p>
            <p>
              <a href="/sports" class="text-reset">Sports</a>
            </p>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
            <p><i class="fas fa-home me-3"></i> Delhi,India</p>
            <p>
              <i class="fas fa-envelope me-3"></i>
              info@example.com
            </p>
            <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
            <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
          </div>
          <!-- Grid column -->
        </div>
        <!-- Grid row -->
      </div>
    </section>
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05)">
      Copyright @ All Rights reserved
      <a class="text-reset fw-bold" href="#">By Nishu kumar</a>
    </div>
  </footer>
</footer>

newsapp/templates/newsapp/index.html
{%extends 'newsapp/base.html' %} {%load static%}
<!-- title -->
{%block title%}
<title>One News | No. 1 News Portal in India</title>
{%endblock%}

<!-- styles -->
{%block styles%}
<link rel="stylesheet" href="{% static 'css/style.css' %}" />
{%endblock%}

<!-- navbar -->
{%block navbar%} {%include "newsapp/navbar.html" %} {%endblock%}
<!-- body -->
{%block body%}
<!-- filtered news title -->
{%if category%}
<h1 class="bg-light text-secondary section-heading">{{category|upper}} News</h1>
{%endif%}
<!-- grid gallery -->
<div class="gallery-grid">
  {%for article in articles%}
  <div class="cards">
    <a href="{% url 'newsapp:NewsDetail' article.slug  %}">
      <img src="{{article.image.url}}" class="card-img-top" alt="..." />
      <p class="date text-secondary">
        <i>Last Updated : {{article.last_updated|date:"M d, Y"}}</i>
      </p>
      <p class="title">{{article.title|truncatechars:50}}</p>
    </a>
  </div>
  {%empty%}
  <h5 class="text-secondary">Sorry ! no articles found</h5>
  <p class="text-secondary">try with a different keyword</p>
  {%endfor%}
</div>
<!-- pagination -->
{% include "newsapp/paginate.html" %} {%endblock%}
<!-- footer -->
{%block footer%}{% include "newsapp/footer.html" %} {%endblock%}

newsapp/templates/newsapp/messages.html
{% if messages %}
   <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
   </ul>
  {% endif %}

newsapp/templates/newsapp/morenewsform.html
{%extends 'newsapp/base_form.html' %}
<!-- form-heading -->
{%block form-heading%}Add More Images and Paragrphs {%endblock%}
<!-- form footer -->
{%block formfooter%}
<a href="/">Cancel</a>
{%endblock%}

newsapp/templates/newsapp/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-light sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><img src={%static 'logo.png' %} alt=""></a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      {% block navlist%}
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <!-- nav menu -->
        {%for category in categories%}
        <li class="nav-item">
          <a
            class="nav-link"
            href="{% url 'newsapp:NewsByCategory' category.slug %}"
          >
            <b> {{category|upper}}</b></a
          >
        </li>
        {%endfor%}
        <!-- all categories -->
        {%if categories%}
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            <b>{{"All Categories"|upper}}</b>
          </a>
          <ul class="dropdown-menu">
            {%for category in categories%}
            <li class="nav-item" style="text-align: center">
              <a class="nav-link" href="/"> <b> {{category|upper}}</b></a>
            </li>
            {%endfor%}
          </ul>
        </li>
        {%endif%}
        <!-- user actions -->
        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
          <a
            href="#"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            {% if user.is_authenticated and user.dp %}
            <img
              title="{{user.username}}"
              height="50"
              width="50"
              style="border-radius: 50%; padding: 5px"
              src="{{user.dp.url}}"
              alt="profile seection"
            />
            {%else%}
            <span class="navbar-toggler-icon mt-2"></span>
            {%endif%}
          </a>
          <ul class="dropdown-menu">
            <li class="nav-item" style="text-align: center">
              <a class="nav-link" href="/admin">
                <b> {{"Dashboard"|upper}}</b></a
              >
            </li>
            <li class="nav-item" style="text-align: center">
              <a
                class="nav-link bg-light"
                href="{% url 'newsapp:CreateArticle' %}"
              >
                <b> Create Article</b></a
              >
            </li>
            <li class="nav-item" style="text-align: center">
              <a
                class="nav-link text-warning"
                href="{% url 'accounts:update' user.id%}"
              >
                <b> Update Profile</b></a
              >
            </li>
            <li class="nav-item" style="text-align: center">
              <a
                class="nav-link text-danger"
                href="{% url 'accounts:logout' %}"
              >
                <b> {{"Sign Out"|upper}}</b></a
              >
            </li>
          </ul>
        </li>
        {% else %}
        <li class="nav-item dropdown">
          <a
            href="#"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            <span class="navbar-toggler-icon mt-2"></span>
          </a>
          <ul class="dropdown-menu">
            <li class="nav-item" style="text-align: center">
              <a class="nav-link" href="{% url 'accounts:login' %}">
                <b> {{"Login"|upper}}</b></a
              >
            </li>
            <li class="nav-item" style="text-align: center">
              <a class="nav-link" href="{% url 'accounts:register' %}">
                <b> {{"Sign Up"|upper}}</b></a
              >
            </li>
          </ul>
        </li>
        {% endif %}
      </ul>
      {%endblock%}
      <form
        method="get"
        class="d-flex"
        role="search"
        action=" {% url 'newsapp:Search' %}"
      >
        <input
          name="search"
          type="search"
          class="form-control me-2"
          placeholder="Search Blogs"
          aria-label="Search"
          style="border: solid 2px"
        />
        <button class="btn btn-secondary" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

newsapp/templates/newsapp/paginate.html
{%if page_obj%}
<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
    <a href="?page=1">&laquo; first</a>
    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">next</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
  </span>
</div>
{%endif%}

newsapp/templates/newsapp/profile.html
{%extends 'newsapp/index.html' %} {%block body%} hi i am
<i>{{profile.name}}</i>
{%endblock%}

newsapp/templates/newsapp/update_article.html
<!-- form-heading -->
{%extends 'newsapp/base_form.html' %}
<!-- form-heading -->
{%block form-heading%} Update Article {%endblock%} {%block moreform%}
<!--  -->
{%if formset%}
<!--  -->
{{formset.management_form}} {%for form in formset%}
<hr />
{{form.as_div}} {%endfor%}
<!--  -->
{%endif%} {%endblock%}
<!-- form footer -->
{%block formfooter%}
<p>last form is given for adding extra images and paragraphs</p>
<a href="/">Cancel</a>
{%endblock%}